const configs={
 polyclinic:{label:'Polyclinic Dataset',records:500,features:[['Age','Age',18,60],['Systolic BP','Systolic_BP',80,220],['Diastolic BP','Diastolic_BP',40,140],['Blood Glucose','Blood_Glucose',2,250],['BMI','BMI',10,60],['Heart Rate','Heart_Rate',40,160],['Parity','Parity',0,10],['Hemoglobin','Hemoglobin',5,20]],model:'model/polyclinic.json'},
 mendeley:{label:'Mendeley Dataset',records:6103,features:[['Age','Age',15,70],['Body Temperature (°F)','Body Temperature(F) ',90,105],['Heart Rate (bpm)','Heart rate(bpm)',40,180],['Systolic BP (mm Hg)','Systolic Blood Pressure(mm Hg)',70,220],['Diastolic BP (mm Hg)','Diastolic Blood Pressure(mm Hg)',40,140],['BMI (kg/m²)','BMI(kg/m 2)',10,60],['HbA1c','Blood Glucose(HbA1c)',2,100],['Fasting Glucose (mg/dl)','Blood Glucose(Fasting hour-mg/dl)',2,300]],model:'model/mendeley.json'},
 uci:{label:'UCI Dataset',records:1014,features:[['Age','Age',15,70],['Systolic BP','SystolicBP',70,220],['Diastolic BP','DiastolicBP',40,140],['Blood Glucose','BS',2,30],['Body Temperature (°F)','BodyTemp',90,105],['Heart Rate','HeartRate',40,180]],model:'model/uci.json'}
};
let models={};
const $=s=>document.querySelector(s);
function relu(x){return Math.max(0,x)}
function softmax(a){let m=Math.max(...a),e=a.map(v=>Math.exp(v-m)),s=e.reduce((x,y)=>x+y,0);return e.map(v=>v/s)}
function predict(model,vals){let x=vals.map((v,i)=>(v-model.mean[i])/model.scale[i]);for(let l=0;l<model.coefs.length;l++){let w=model.coefs[l],b=model.intercepts[l];let out=b.map((bv,j)=>bv+x.reduce((sum,xi,i)=>sum+xi*w[i][j],0));x=l<model.coefs.length-1?out.map(relu):softmax(out)}return x}
async function loadModel(key){if(!models[key]){let r=await fetch(configs[key].model);models[key]=await r.json()}return models[key]}
function renderForm(){let key=$('#dataset').value,c=configs[key];$('#datasetInfo').textContent=`${c.label}: ${c.records.toLocaleString()} records. Enter the clinical measurements used by this dataset's ANN.`;$('#predictionForm').innerHTML=c.features.map((f,i)=>`<div class="field"><label>${f[0]}</label><input id="f${i}" type="number" step="any" min="${f[2]}" max="${f[3]}" required placeholder="Enter ${f[0]}"></div>`).join('')+`<button class="submit" type="submit">Predict Risk</button>`;renderPerformance()}
async function renderPerformance(){let m=await loadModel($('#dataset').value);$('#metrics').innerHTML=`<div class="metric"><span>Dataset Records</span><b>${m.records.toLocaleString()}</b></div><div class="metric"><span>ANN Accuracy</span><b>${(m.accuracy*100).toFixed(2)}%</b></div><div class="metric"><span>Classes</span><b>3</b></div><div class="metric"><span>Architecture</span><b>64–32–16</b></div>`;let labels=m.classes;let cm=m.confusion_matrix;let html='<div></div>'+labels.map(x=>`<div class="head">Pred. ${x.replace(' Risk','')}</div>`).join('');labels.forEach((x,i)=>{html+=`<div class="head">Actual ${x.replace(' Risk','')}</div>`+cm[i].map(v=>`<div>${v}</div>`).join('')});$('#confusion').innerHTML=html}
$('#dataset').addEventListener('change',renderForm);
$('#predictionForm').addEventListener('submit',async e=>{e.preventDefault();let key=$('#dataset').value,c=configs[key],m=await loadModel(key),vals=c.features.map((_,i)=>Number($('#f'+i).value));if(vals.some(v=>!Number.isFinite(v))){return}let p=predict(m,vals),idx=p.indexOf(Math.max(...p)),name=m.classes[idx],cls=idx===0?'low':idx===1?'medium':'high';$('#result').innerHTML=`<div><div class="eyebrow" style="text-align:center">PREDICTED MATERNAL RISK</div><div class="risk ${cls}">${name}</div><div class="prob">${m.classes.map((n,i)=>`<div><b>${n}</b> — ${(p[i]*100).toFixed(1)}%</div><div class="bar"><i style="width:${p[i]*100}%"></i></div>`).join('')}</div></div>`});
renderForm();
